Only add binlog-space-limit for percona image
presslabs/mysql-operator pull request #601
Opened 2020-09-15 02:28 UTC by bananaappletw

closes/fixes #591

---
 - [x] I've made sure the [Changelog.md](https://github.com/presslabs/mysql-operator/blob/master/Changelog.md) will remain up-to-date after this PR is merged.

2020-09-15 18:05 UTC, AMecea requested changes

2020-09-15 18:05 UTC, AMecea commented on pkg/internal/mysqlcluster/defaults.go
> +			if matched, err := regexp.MatchString("([a-z.]+/)*percona(:.+)?", cluster.Spec.Image); err != nil && matched {
Let's define a utility function `IsPerconaImage` that will try to identify the source of the underlay image. Here is an example: https://github.com/presslabs/mysql-operator/blob/677a2ce5d364270604b8a0645e19a7df742f36f1/pkg/internal/mysqlcluster/mysqlcluster.go#L224

Also, please use `GetMysqlImage()` which computes the image based on more rules.

```suggestion
			if cluster.IsPerconaImage() {
```

2020-09-16 02:14 UTC, bananaappletw commented
@AMecea 
Changed.
Please review again, thank you.

2020-09-16 18:10 UTC, AMecea approved these changes

2020-09-16 18:11 UTC, merged